name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout no codigo
      uses: actions/checkout@v2

    - name: setando o nodeJs 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Instalando as dependencias
      run: npm install

    - name: Rodando os testes
      run: npm test

    - name: Buildando a Aplicacao
      run: npm run build
      if: success()

    - name: Fazendo o Deploy
      run: echo "Deploying..."
      if: success()